### ISSUE TITLE
[BUG/ISSUE] GCHP simulation crashed with >1000 cores no matter setting WRITE_RESTART_BY_OSERVER YES/NO on Pleiades

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/GCHP#133]
### Description of the problem
I am running a GCHP v13.0.0 C720 TransportTracer simulation on Pleiades, but it always crashed at writing diagnostic file with total cores > 1000. I have tried setting WRITE_RESTART_BY_OSERVER YES or NO, but both settings still got crashing when total cores > 1000 (Specifically 1200 total cores). The same simulation ran successfully when I change the total cores < 1000 (960 total cores). Any suggestions on simulation settings on Pleiades would be appreciated!

### GEOS-Chem version
GCHP v13.0.0

### Description of code modifications
The configuration files are all left as default.

### Log files
- Build log (if applicable):
- Run log (if applicable): 
[run-960.log](https://github.com/geoschem/GCHP/files/7033757/run-960.log)
[run-1200.log](https://github.com/geoschem/GCHP/files/7033760/run-1200.log)

- Run script (if applicable):
[run-960.pbs.txt](https://github.com/geoschem/GCHP/files/7033774/run-960.pbs.txt)
[run-1200.pbs.txt](https://github.com/geoschem/GCHP/files/7033775/run-1200.pbs.txt)

### Software versions
- Compilers (Intel or GNU, and version): Intel 19.1.3
- NetCDF version: 4.8.0
- MPI version: MPT 2.23
- ESMF version: 8.0.0

**Comment by LiamBindle** [comment]
@lizziel @sdeastham Do you have any ideas? Just to clarify, it's crashing when it goes to write the HISTORY diagnostics. 


### For convenience

<details>
  <summary>Here is the last non-error part of the 1200 core log file</summary>

```
 AGCM Date: 2019/01/01  Time: 00:50:00  Throughput(days/day)[Avg Tot Run]:  129.8  122.3  123.8  TimeRemaining(Est) 000:01:00   45.9% :  44.4% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  7.393E+04  0.000E+00
 AGCM Date: 2019/01/01  Time: 00:55:00  Throughput(days/day)[Avg Tot Run]:  127.9  112.0  113.2  TimeRemaining(Est) 000:00:58   45.9% :  44.4% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  7.393E+04  0.000E+00
 
 Writing:     72 Slices to File:  OutputDir/GCHP.SpeciesConc.20190101_0030z.nc4
<errors start here>
```

</details>

<details>
  <summary>Here is the stack trace</summary>

```
MPT: #1  0x00002aaaab8f10e6 in mpi_sgi_system (
MPT: #2  MPI_SGI_stacktraceback (
MPT:     header=header@entry=0x7fffffff63d0 "MPT ERROR: Rank 940(g:940) received signal SIGSEGV(11).\n\tProcess ID: 48102, Host: r587i3n4, Program: /nobackupp12/dzhang8/GCHP-v13.0.0/rundir-c720-tracers/gchp\n\tMPT Version: HPE MPT 2.23  09/13/20 02:"...) at sig.c:340
MPT: #3  0x00002aaaab8f12e6 in first_arriver_handler (signo=signo@entry=11, 
MPT:     stack_trace_sem=stack_trace_sem@entry=0x2aaab7360080) at sig.c:489
MPT: #4  0x00002aaaab8f1573 in slave_sig_handler (signo=11, 
MPT:     siginfo=<optimized out>, extra=<optimized out>) at sig.c:565
MPT: #5  <signal handler called>
MPT: #6  0x0000000000000000 in ?? ()
MPT: #7  0x00002aaaab81e455 in MPI_SGI_request_rdma (dom=<optimized out>, 
MPT:     modes=modes@entry=8, loc_addr=loc_addr@entry=0x8ca445e0, 
MPT:     value=value@entry=0x0, rad=rad@entry=0x7fffffff6e50, len=len@entry=4)
MPT:     at req.c:985
MPT: #8  0x00002aaaab8da7ab in rdma_write (len=4, locp=0x8ca445e0, 
MPT:     rad=0x7fffffff6e50, dom=<optimized out>) at rdma.c:113
MPT: #9  MPI_SGI_rdma_put (area=<optimized out>, rank=rank@entry=25, 
MPT:     remp=<optimized out>, locp=0x8ca445e0, len=4, isamo=isamo@entry=0)
MPT:     at rdma.c:426
MPT: #10 0x00002aaaab8d57bc in launch_op (opinfo=0x89fdbb10, rank=25, 
MPT:     winptr=0x8da99560) at put.c:129
MPT: #11 enqueue_op (flags=0, opinfo=<optimized out>, target=0x8e8a7760, rank=25, 
MPT:     winptr=0x8da99560) at put.c:172
MPT: #12 rdma_put (flags=0, winptr=0x8da99560, target_datatype=<optimized out>, 
MPT:     target_count=<optimized out>, target_disp=<optimized out>, 
MPT:     target_rank=25, origin_datatype=<optimized out>, 
MPT:     origin_count=<optimized out>, origin_addr=<optimized out>) at put.c:217
MPT: #13 MPI_SGI_put (flags=0, win=<optimized out>, 
MPT:     target_datatype=<optimized out>, target_count=<optimized out>, 
MPT:     target_disp=<optimized out>, target_rank=25, 
MPT:     origin_datatype=<optimized out>, origin_count=<optimized out>, 
MPT:     origin_addr=<optimized out>) at put.c:271
MPT: #14 PMPI_Put (origin_addr=<optimized out>, origin_count=<optimized out>, 
MPT:     origin_datatype=<optimized out>, target_rank=25, 
MPT:     target_disp=<optimized out>, target_count=<optimized out>, 
MPT:     target_datatype=81, win=5) at put.c:313
MPT: #15 0x00002aaaab8d6eca in pmpi_put__ () from /nasa/hpe/mpt/2.23/lib/libmpi.so
MPT: #16 0x000000000196e209 in pfio_serverthreadmod::receive_output_data (
MPT:     this=<not associated>, rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/ServerThread.F90:1061
MPT: #17 0x0000000001941bab in pfio_baseservermod::receive_output_data (
MPT:     this=<not associated>, rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/BaseServer.F90:69
MPT: #18 0x0000000001970c47 in pfio_serverthreadmod::handle_done_collective_stage (
MPT:     this=<not associated>, message=..., rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/ServerThread.F90:1135
MPT: #19 0x000000000192c8bf in pfio_messagevisitormod::handle (this=0x0, 
MPT:     message=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/MessageVisitor.F90:93
MPT: #20 0x00000000019fcd0d in pfio_abstractmessagemod::dispatch (this=0x0, 
MPT:     visitor=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/AbstractMessage.F90:110
MPT: #21 0x000000000193cc75 in pfio_simplesocketmod::send (this=<not associated>, 
MPT:     message=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/SimpleSocket.F90:105
MPT: #22 0x000000000197f876 in pfio_clientthreadmod::done_collective_stage (
MPT:     this=<not associated>)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/ClientThread.F90:428
MPT: #23 0x0000000001987c00 in pfio_clientmanagermod::done_collective_stage (
MPT:     this=<not associated>, unusable=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/pfio/ClientManager.F90:340
MPT: #24 0x00000000016ff28b in mapl_historygridcompmod::run (gc=..., import=..., 
MPT:     export=..., 
MPT:     clock=<error reading variable: Cannot access memory at address 0x4>, 
MPT:     rc=<error reading variable: Cannot access memory at address 0x0>)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_HistoryGridComp.F90:3570
MPT: #25 0x0000000001f67331 in ESMCI::FTable::callVFuncPtr(char const*, ESMCI::VM*, int*) ()
MPT: #26 0x0000000001f675d7 in ESMCI_FTableCallEntryPointVMHop ()
MPT: #27 0x0000000001dc9394 in ESMCI::VMK::enter(ESMCI::VMKPlan*, void*, void*) ()
MPT: #28 0x0000000001f69f15 in ESMCI::VM::enter(ESMCI::VMPlan*, void*, void*) ()
MPT: #29 0x0000000001f6569c in c_esmc_ftablecallentrypointvm_ ()
MPT: #30 0x0000000001c9a16d in esmf_compmod_mp_esmf_compexecute_ ()
MPT: #31 0x0000000001aa0281 in esmf_gridcompmod_mp_esmf_gridcomprun_ ()
MPT: #32 0x00000000013edd3e in mapl_genericmod::mapl_genericwrapper (gc=..., 
MPT:     import=..., export=..., 
MPT:     clock=<error reading variable: Cannot access memory at address 0x4>, 
MPT:     rc=<error reading variable: Cannot access memory at address 0x0>)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_Generic.F90:1824
MPT: #33 0x0000000001f67331 in ESMCI::FTable::callVFuncPtr(char const*, ESMCI::VM*, int*) ()
MPT: #34 0x0000000001f675d7 in ESMCI_FTableCallEntryPointVMHop ()
MPT: #35 0x0000000001dc9394 in ESMCI::VMK::enter(ESMCI::VMKPlan*, void*, void*) ()
MPT: #36 0x0000000001f69f15 in ESMCI::VM::enter(ESMCI::VMPlan*, void*, void*) ()
MPT: #37 0x0000000001f6569c in c_esmc_ftablecallentrypointvm_ ()
MPT: #38 0x0000000001c9a16d in esmf_compmod_mp_esmf_compexecute_ ()
MPT: #39 0x0000000001aa0281 in esmf_gridcompmod_mp_esmf_gridcomprun_ ()
MPT: #40 0x00000000014962aa in mapl_capgridcompmod::step (this=<not associated>, 
MPT:     rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_CapGridComp.F90:1125
MPT: #41 0x00000000014958fc in mapl_capgridcompmod::run_mapl_gridcomp (gc=..., 
MPT:     rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_CapGridComp.F90:1012
MPT: #42 0x0000000001495554 in mapl_capgridcompmod::run_gc (gc=..., import=..., 
MPT:     export=..., 
MPT:     clock=<error reading variable: Cannot access memory at address 0x4>, 
MPT:     rc=<error reading variable: Cannot access memory at address 0x0>)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_CapGridComp.F90:732
MPT: #43 0x0000000001f67331 in ESMCI::FTable::callVFuncPtr(char const*, ESMCI::VM*, int*) ()
MPT: #44 0x0000000001f675d7 in ESMCI_FTableCallEntryPointVMHop ()
MPT: #45 0x0000000001dc9394 in ESMCI::VMK::enter(ESMCI::VMKPlan*, void*, void*) ()
MPT: #46 0x0000000001f69f15 in ESMCI::VM::enter(ESMCI::VMPlan*, void*, void*) ()
MPT: #47 0x0000000001f6569c in c_esmc_ftablecallentrypointvm_ ()
MPT: #48 0x0000000001c9a16d in esmf_compmod_mp_esmf_compexecute_ ()
MPT: #49 0x0000000001aa0281 in esmf_gridcompmod_mp_esmf_gridcomprun_ ()
MPT: #50 0x0000000001498bd3 in mapl_capgridcompmod::run (this=<not associated>, 
MPT:     rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_CapGridComp.F90:861
MPT: #51 0x00000000014910d2 in mapl_capmod::run_model (
MPT:     this=0x34996a0 <gchpctm_main_$CAP.0.1>, mapl_comm=..., 
MPT:     unusable=0x2aca6b138080, 
MPT:     rc=<error reading variable: Cannot access memory at address 0x4>)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_Cap.F90:323
MPT: #52 0x0000000001490b48 in mapl_capmod::run_member (this=<not associated>, 
MPT:     rc=0)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_Cap.F90:198
MPT: #53 0x000000000148f879 in mapl_capmod::run_ensemble (this=<not associated>, 
MPT:     unusable=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_Cap.F90:157
MPT: #54 0x000000000148ef5f in mapl_capmod::run (this=<not associated>, 
MPT:     unusable=0xffffffff00000000, rc=1796440192)
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/MAPL/base/MAPL_Cap.F90:131
MPT: #55 0x000000000042723d in gchpctm_main ()
MPT:     at /nobackup/dzhang8/GCHP-v13.0.0/GCHP.13.0.0/src/GCHPctm.F90:29
MPT: #56 0x0000000000426292 in main ()
MPT: #57 0x00002aaaad39ba35 in __libc_start_main () from /lib64/libc.so.6
MPT: #58 0x00000000004261a9 in _start () at ../sysdeps/x86_64/start.S:118
```

</details>
