### ISSUE TITLE
[BUG/ISSUE] MPI_ABORT errors when ran GCHP

### ISSUE THREAD

**Issue by XiaoyuSun-n** [geoschem/GCHP#94]
### Description of the problem
Hello, I am trying to run gchp and used the input files as same as downloaded file. But there are errors. The error showed:

```
FATAL: mpp_domains_define.inc: not all the pe_end are in the pelist


FATAL: mpp_domains_define.inc: not all the pe_end are in the pelist

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

I have only started to use GCHP recently and I used GCClassic before. So I don't quite understand why there is this error.
Any suggestions appreciated!

### GEOS-Chem version
GCHP  v13 downloaded from GCHP git webpage (main branch)

### Log files
- Run log (if applicable):
[GC.log](https://github.com/geoschem/GCHP/files/6376901/GC.log)

- Run script (if applicable):
[test.slurm.txt](https://github.com/geoschem/GCHP/files/6377075/test.slurm.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/6376933/runConfig.sh.txt)

**Comment by WilliamDowns** [comment]
GCHP uses MPI rather than OMP for most of its parallel operations. Your error indicates a confusion in MPI regarding how many processes it should initialize to run the GCHP executable. You may be able to resolve this specific issue by using the `mpirun` command to run your application while specifying the number of processes in the command call. You should replace `./gchp 2>&1 | tee GC.log` with `mpirun -np 24 ./gchp 2>&1 | tee GC.log`. 

You may encounter more issues related to your MPI version (2.1.6). We recommend using OpenMPI >= 4.0 if it is available to you on your cluster (>=3.0 may also improve chances of success). We also provide instructions for building GCHP and its requisite libraries [using Spack](https://gchp.readthedocs.io/en/latest/supplement/spack.htmll), though this should be a last resort given your cluster seems to have most libraries already built.

**Comment by XiaoyuSun-n** [comment]
Thanks for your kind and fast reponse.

I changed the command to mpirun and, as you said, I have encountered other error messages. I then changed the OpenMPI version to 3.1.5 which is the highest version that is currently installed on our cluster, but the following error still occurs.
```
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
[bcn1664:430817] *** An error occurred in MPI_Init_thread
[bcn1664:430817] *** on a NULL communicator
[bcn1664:430817] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430817] ***    and potentially your MPI job)
[bcn1664:430817] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
[bcn1664:430816] *** An error occurred in MPI_Init_thread
[bcn1664:430816] *** on a NULL communicator
[bcn1664:430816] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430816] ***    and potentially your MPI job)
[bcn1664:430824] *** An error occurred in MPI_Init_thread
[bcn1664:430824] *** on a NULL communicator
[bcn1664:430824] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430824] ***    and potentially your MPI job)
[bcn1664:430824] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[bcn1664:430816] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
[bcn1664:430825] *** An error occurred in MPI_Init_thread
[bcn1664:430825] *** on a NULL communicator
[bcn1664:430825] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430825] ***    and potentially your MPI job)
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
[bcn1664:430825] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[bcn1664:430814] *** An error occurred in MPI_Init_thread
[bcn1664:430814] *** on a NULL communicator
[bcn1664:430814] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430814] ***    and potentially your MPI job)
[bcn1664:430814] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[bcn1664:430810] *** An error occurred in MPI_Init_thread
[bcn1664:430810] *** on a NULL communicator
[bcn1664:430810] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430810] ***    and potentially your MPI job)
[bcn1664:430810] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[bcn1664:430826] *** An error occurred in MPI_Init_thread
[bcn1664:430826] *** on a NULL communicator
[bcn1664:430826] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[bcn1664:430826] ***    and potentially your MPI job)
[bcn1664:430826] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4891,1],7]
  Exit code:    1
```

Does this mean I need a higher version of MPI? Or perhaps there was something else that might have caused the error? And I will contact to our administrator and try to get OpenMPI>=4.0 later. Thanks again.

**Comment by WilliamDowns** [comment]
I'm not sure exactly what that error indicates, but I'd recommend recompiling GCHP and ESMF with the new MPI version loaded.

**Comment by XiaoyuSun-n** [comment]
Thanks for your reply.
I recompiling GCHP and ESMF with OpenMPI 3.1.5 loaded, and ran GCHP again, there are another errors shows:
```
      MAPL: No configure file specified for logging layer.  Using defaults.
     SHMEM: NumCores per Node = 24
     SHMEM: NumNodes in use   = 1
     SHMEM: Total PEs         = 24
     SHMEM: NumNodes in use  = 1
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
pe=00000 FAIL at line=00255    MAPL_CapGridComp.F90                     <something impossible happened>
pe=00000 FAIL at line=00849    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00322    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00198    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00131    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00029    GCHPctm.F90                              <status=1>
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
pe=00008 FAIL at line=00255    MAPL_CapGridComp.F90                     <something impossible happened>
pe=00008 FAIL at line=00849    MAPL_CapGridComp.F90                     <status=1>
pe=00008 FAIL at line=00322    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00198    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00131    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00029    GCHPctm.F90                              <status=1>
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
pe=00004 FAIL at line=00255    MAPL_CapGridComp.F90                     <something impossible happened>
pe=00004 FAIL at line=00849    MAPL_CapGridComp.F90                     <status=1>
pe=00004 FAIL at line=00322    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00198    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00131    MAPL_Cap.F90                             <status=1>
pe=00004 FAIL at line=00029    GCHPctm.F90                              <status=1>
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
[bcn1716:23012] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[bcn1716:23012] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
The MPI version I used this time is OpenMPI 3.1.5, and I saw the vedio 'Compiling GCHP' on the YouTube channel that he also used OpenMPI version 3.1, so I wonder if this time the problem is not caused by the low MPI version? 
Thanks again for your time and help.

**Comment by WilliamDowns** [comment]
I just did a successful 1-hour test with OpenMPI 3.1.5 on my system, so you're right that the version should not be the issue here. I've encountered your error before when testing various MPI versions, though. It's possible there's some odd library mismatch happening. In `CodeDir/src/MAPL/base/MAPL_CapGridComp.F90`, could you replace:

```
    call ESMF_VMGet(cap%vm, petcount=npes, mpicommunicator=comm, rc=status)
    _VERIFY(status)
     _ASSERT(CoresPerNode <= npes, 'something impossible happened')
```

with

```
    call ESMF_VMGet(cap%vm, petcount=npes, mpicommunicator=comm, rc=status)
    _VERIFY(status)
    write(*,*) 'CoresPerNode', CoresPerNode
    write(*,*) 'npes', npes
     _ASSERT(CoresPerNode <= npes, 'something impossible happened')
```

and recompile your GCHP executable and post the output from running the model again? Also, please post the output from `ldd -v gchp` here.

**Comment by XiaoyuSun-n** [comment]
Thanks for your answer. I did as you said, and here is the error message from the output after running:

```
     MAPL: No configure file specified for logging layer.  Using defaults.
     SHMEM: NumCores per Node = 24
     SHMEM: NumNodes in use   = 1
     SHMEM: Total PEs         = 24
     SHMEM: NumNodes in use  = 1
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
 NOT using buffer I/O for file: cap_restart
 CoresPerNode          24
 npes           1
pe=00000 FAIL at line=00257    MAPL_CapGridComp.F90                     <something impossible happened>
pe=00000 FAIL at line=00851    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00322    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00198    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00131    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00029    GCHPctm.F90                              <status=1>
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 CoresPerNode          24
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```
And the ldd output is in the lddgchp.log
[lddgchp.log](https://github.com/geoschem/GCHP/files/6390201/lddgchp.log)

**Comment by WilliamDowns** [comment]
I don't see anything obviously amiss in that `ldd` log. What version of ESMF are you using? >=8.0.0 is required, though 8.1.0 and 8.2.0 (beta) are not officially supported yet. 

@tclune ESMF_VMGet is detecting only 1 PE rather than 24. This user is using OpenMPI 3.1.5, and I've encountered the same issue previously using Intel MPI 2021.2. Any advice is greatly appreciated.

**Comment by tclune** [comment]
If ESMF is compiled in serial that would produce these symptoms.   Or if the mpi launch only requested 1 PE.

I'm bringing in @mathomp4 in case he has other thoughts.

**Comment by mathomp4** [comment]
> If ESMF is compiled in serial that would produce these symptoms. Or if the mpi launch only requested 1 PE.
> 
> I'm bringing in @mathomp4 in case he has other thoughts.

Indeed, this line from the ldd log seems to indicate that ESMF was not compiled for MPI:
```
/home/hbkxisun/esmf/lib/libO/Linux.gfortran.64.mpiuni.default/libesmf.so (0x00002b4459512000)
```
`mpiuni` is the "no MPI uniprocessor" version of ESMF. You should rebuild ESMF with `ESMF_COMM=openmpi` and link to that version (probably be in `Linux.gfortran.64.openmpi.default`)

**Comment by WilliamDowns** [comment]
Thanks very much to you both for your help. @xiaoyu-ss, if you recompile ESMF with OpenMPI 3.1.5 loaded + `export ESMF_COMM=openmpi` set in your environment, then recompile GCHP, you should be able to progress past this error.

**Comment by XiaoyuSun-n** [comment]
I really appreciate both of your help. 
I export the variable and link a new version and it seems that it starts to run. Thanks.
But when it begins doing chemistry, there is some errors about invalid memory reference. 
```
  --- Do convection now
  --- Convection done!
  --- Do drydep now
      Use FULL PBL:  F
  --- Drydep done!
  --- Do emissions now
  --- Emissions done!
  --- Do turbulence now
  --- Turbulence done!
  --- Do chemistry now
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
     - DO_STRAT_CHEM: Linearized strat chemistry at 2016/07/01 00:20
     - LINOZ_CHEM3: Doing LINOZ
===============================================================================
GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod
===============================================================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2aaaacf8462f in ???
#0  0x2aaaacf8462f in ???
...
```
(There are a lot of error messages below, so I've attached the log file to avoid making it too long.)
[GC.log](https://github.com/geoschem/GCHP/files/6404284/GC.log)

I don't konw how to fix this. Could you give me some suggesstions abou it?
Thanks very much.

**Comment by WilliamDowns** [comment]
@sdeastham Any thoughts on what could lead to this error? EDIT: Not likely the actual culprit, see below.

**Comment by WilliamDowns** [comment]
@xiaoyu-ss it seems like there's an issue with your restart file. In your log file, all species are being initialized from background values rather than values from the restart file:

```
Initialized species from INTERNAL state: ACET
    WARNING: using background values from species database
 Initialized species from INTERNAL state: ACTA
    WARNING: using background values from species database
 Initialized species from INTERNAL state: AERI
    WARNING: using background values from species database
 Initialized species from INTERNAL state: ALD2
    WARNING: using background values from species database
 Initialized species from INTERNAL state: ALK4
    WARNING: using background values from species database
```

Can you try re-downloading `initial_GEOSChem_rst.c24_fullchem.nc` and running again? It's also possible this file (or a file called `GCHP.Restart.fullchem.20190701_0000z.c24.nc4`) already exists on your system, but is improperly linked in your run directory because it's not in the expected location in ExtData. If this is the case, do `rm initial_GEOSChem_rst.c24_fullchem.nc` in your run directory and copy the restart file (renaming it to `initial_GEOSChem_rst.c24_fullchem.nc` if necessary) to your run directory.

**Comment by sdeastham** [comment]
This could also be the cause of the "excessive fall velocity" issue. If the entire atmosphere is set to default values for all species, the physics and chemistry will get very strange.

**Comment by XiaoyuSun-n** [comment]
Thank you both, I modified my restart file and it worked, it ran to the last part, but there seems to be something wrong with the last part of cap_restart. But I don't quite understand the meaning of the mistakes in this part. Could you give me some advice? 
Thank you very much for your time and help.
[GC.log](https://github.com/geoschem/GCHP/files/6414414/GC.log)

**Comment by mathomp4** [comment]
@xiaoyu-ss Hmm. That error is right around a change recently made in MAPL where some [MPI comm changes](https://github.com/GEOS-ESM/MAPL/pull/811) were done. I know there have been MPI clean up oddities in MAPL-as-library so maybe this is one of the reasons that code was changed?

**Comment by WilliamDowns** [comment]
This issue is the same as #88 and will be fixed in GCHP 13.1.0 (and I believe is currently fixed by some of the MAPL updates in the `dev` branch). Don't worry about this error as it should be benign: you should now have a checkpoint file (name starts with `gcchem_internal_checkpoint`) and also SpeciesConc, Metrics, and Emissions files in your `OutputDir` directory.

**Comment by XiaoyuSun-n** [comment]
Yes, I see the output files.
Thank you very much. It's very kind of you to help me a lot. I'm looking forward to the new version.

**Comment by sdeastham** [comment]
Is the file `cap_restart` still generated and does it contain the text `20160701 010000`, incidentally? It's not strictly necessary, but does simplify setting up segmented runs.

**Comment by XiaoyuSun-n** [comment]
Yes, the cap_restart file is generated and it contains the text  20160701 010000.
Here is another question about the Output file. Because I set the input.geos file to run for 1 hour, and {collection}.frequency and {collection}.duration in the HISTORY.rc file is set to 010000. So I expect the output file to be written every hour, but the suffix of my output file end at 0030z.nc, maybe is there something wrong with it when writting the output files? Or is that the naming convention for the output file?

**Comment by WilliamDowns** [comment]
Not to worry, that is the current naming convention for time-averaged GCHP output files (using the midpoint of the period as the filename rather than the beginning of the period as GC Classic does).

**Comment by lizziel** [comment]
Changing start and end time in `input.geos `actually will have no effect on GCHP. You need to set start/end in `runConfig.sh`, which updates `CAP.rc` as a pre-run step (sourcing `runConfig.sh` should be in your run script). If you are running a standard full chemistry simulation it comes set up to run 1-hour by default.

For version prior to 13.1 all time-averaged filenames contain averaging period mid-point. Please note that starting in 13.1, however, they will includes the start of averaging period instead to match GEOS-Chem Classic.
